"use client";

import { useState } from "react";

function jsonToYaml(value: unknown, indent = 0): string { const pad = "  ".repeat(indent); if (value === null) return "null"; if (typeof value === "string") return value === "" || /[:\n#&*!|>%@`]/.test(value) || value.trim() !== value ? JSON.stringify(value) : value; if (typeof value === "number" || typeof value === "boolean") return String(value); if (Array.isArray(value)) { if (!value.length) return "[]"; return value.map((item) => { if (typeof item === "object" && item !== null) { const lines = jsonToYaml(item, indent + 1).split("\n"); return `${pad}- ${lines[0]}${lines.length > 1 ? `\n${lines.slice(1).map((line) => `${pad}  ${line.trimStart()}`).join("\n")}` : ""}`; } return `${pad}- ${jsonToYaml(item, indent)}`; }).join("\n"); } if (typeof value === "object") return Object.entries(value as Record<string, unknown>).map(([key, item]) => typeof item === "object" && item !== null ? `${pad}${key}:\n${jsonToYaml(item, indent + 1)}` : `${pad}${key}: ${jsonToYaml(item, 0)}`).join("\n"); return String(value); }
function yamlToJson(text: string): unknown { try { return JSON.parse(text); } catch { /* continue with the simple YAML reader */ } const lines = text.replace(/\r\n/g, "\n").split("\n").map((line) => line.replace(/\t/g, "  ")).filter((line) => line.trim() && !line.trim().startsWith("#")); if (lines.length && lines.every((line) => line.trimStart().startsWith("- "))) return lines.map((line) => { const value = line.trim().slice(2); try { return JSON.parse(value); } catch { return value; } }); const result: Record<string, unknown> = {}; for (const line of lines) { const separator = line.indexOf(":"); if (separator < 0) throw new Error(`Unsupported YAML line: ${line.trim()}`); const key = line.slice(0, separator).trim(); const value = line.slice(separator + 1).trim(); if (!value) { result[key] = null; continue; } try { result[key] = JSON.parse(value); } catch { result[key] = value; } } return result; }
async function copyText(value: string) { try { await navigator.clipboard.writeText(value); return true; } catch { return false; } }

export default function Home() {
  const [input, setInput] = useState('{\n  "project": "book-dev",\n  "active": true,\n  "tools": ["json", "yaml"]\n}');
  const [output, setOutput] = useState(""); const [mode, setMode] = useState("PRETTY"); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  function transform(nextMode: string) { setMode(nextMode); setError(""); try { if (nextMode === "PRETTY") setOutput(JSON.stringify(JSON.parse(input), null, 2)); else if (nextMode === "MINIFY") setOutput(JSON.stringify(JSON.parse(input))); else if (nextMode === "JSON → YAML") setOutput(jsonToYaml(JSON.parse(input))); else setOutput(JSON.stringify(yamlToJson(input), null, 2)); } catch (cause) { setOutput(""); setError(cause instanceof Error ? cause.message : "Could not transform this document."); } }
  async function copy() { if (await copyText(output)) { setCopied(true); window.setTimeout(() => setCopied(false), 1600); } }
  return <main className="pattern-shell"><header className="pattern-header"><div className="pattern-brand"><span>BOOK / UTILITY</span><strong>03—24</strong></div><div><p className="eyebrow">FORMAT STUDIO / CLIENT-SIDE</p><h1>Pull the<br /><em>pattern.</em></h1><p className="lede">A small drafting table for moving structured data between clean shapes.</p></div><div className="header-note"><span>NO API KEY</span><strong>LOCAL</strong><span>nothing leaves this cloth</span></div></header><div className="drafting-grid" aria-hidden="true">{Array.from({ length: 9 }, (_, index) => <span key={index} />)}</div><section className="drafting-table" aria-label="JSON and YAML converter"><div className="table-top"><div><span className="section-label">01 / CHOOSE A TRANSFORMATION</span><h2>Lay out the pieces.</h2></div><span className="format-status">{mode} / READY</span></div><div className="mode-row">{["PRETTY", "MINIFY", "JSON → YAML", "YAML → JSON"].map((item) => <button type="button" className={mode === item ? "active" : ""} key={item} onClick={() => transform(item)} aria-pressed={mode === item}><span className="cord" />{item}<small>{item === "PRETTY" ? "space the seams" : item === "MINIFY" ? "cut the excess" : item === "JSON → YAML" ? "change the weave" : "read it back"}</small></button>)}</div><div className="pattern-pieces"><div className="piece"><label htmlFor="source"><span>02 / SOURCE PIECE</span><small>{input.length} chars</small></label><textarea id="source" value={input} onChange={(event) => setInput(event.target.value)} spellCheck={false} /><div className="piece-footer"><span>EDITABLE</span><button type="button" onClick={() => setInput("")}>Clear cloth</button></div></div><div className="pull-cord" aria-hidden="true"><span>pull</span><i /></div><div className="piece"><div className="piece-label"><span>03 / FINISHED PIECE</span><small>{output.length} chars</small></div><output className={`result ${error ? "has-error" : ""}`} aria-live="polite">{error ? error : output || <span className="result-placeholder">Choose a cut to see the finished shape.</span>}</output><div className="piece-footer"><span>{error ? "CHECK INPUT" : "READ ONLY"}</span><button type="button" disabled={!output} onClick={() => void copy()}>{copied ? "Copied" : "Copy piece ↗"}</button></div></div></div><div className="table-bottom"><button className="primary-action" type="button" onClick={() => transform(mode)}>Pull {mode.toLowerCase()} <span>→</span></button><p>Simple YAML support for everyday objects and arrays.<br />Everything runs in this tab.</p></div></section><footer className="pattern-footer"><span>JSON CONVERTER / CUTTING TABLE 01</span><span>JSON · YAML · NO SERVER</span></footer></main>;
}
